[tool.pyprojectx]
poetry = "poetry"
pdm = "pdm"
jupyter = "jupyter"
black = "black"
ruff = "ruff"
pre-commit = "pre-commit"
http = "httpie"
scipy = ["scipy", "matplotlib", "ipython", "jupyter", "pandas", "sympy", "nose"]

[tool.pyprojectx.aliases]
notebook = "jupyter notebook -y"
scipy-notebook = "@scipy: jupyter notebook -y"
