
[tool.pyprojectx]
# commonly used tools
black = "black"
#poetry = "poetry"
#pdm = "pdm"
#ruff = "ruff"
#pre-commit = "pre-commit"
#jupyter = ["jupyter", "."]

[tool.pyprojectx.aliases]
# example aliases
black = "black src tests"
ruff = "ruff src tests --fix"
#install = "poetry install"
#run = "poetry run"
#outdated = "poetry show --outdated"
clean = "rm -rf .venv .pytest_cache dist"
#clean-all = "pw@ clean && rm -rf .pyprojectx"
#test = "poetry run pytest"
#check-ruff = "ruff src tests"
#check-black = "black src tests --check"
#check = "pw@ check-black && pw@ check-ruff && pw@ test"
#build = "pw@ install && pw@ check && pw@ poetry build"
#notebook = "jupyter notebook -y"

[tool.pyprojectx.os.win.aliases]
# example os specific aliases
clean = "rmdir /s/q .venv .pytest_cache dist"
#clean-all = "pw@ clean & rmdir /s/q .pyprojectx"
