name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build ${{ matrix.os }} / ${{ matrix.python-version }} ${{ matrix.suffix }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        os: [ Ubuntu, Windows ]
#        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
        python-version: [ "3.10" ]
        include:
          - os: Ubuntu
            image: ubuntu-latest
          - os: Windows
            image: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Linux Build and test
        if: ${{ matrix.os == Ubuntu }}
        run: ./pw build

      - name: Windows Build and test
        if: ${{ matrix.os == Windows }}
        shell: cmd
        run: pw.bat build
