name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache .pyprojectx
        uses: actions/cache@v2
        env:
          cache-name: .pyprojectx
        with:
          path: .pyprojectx
          key: pyprojectx

      - name: Build release
        run: |
          python pw prep-release
          python pw build

      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: .changelog.md
          files: wrappers.zip

      - name: Publish to Pypi
        run: python pw publish --password ${{ secrets.PYPI_TOKEN }}
